pull_request_rules:
  - name: Merge with `ready-to-merge` label
    conditions:
      - check-success=test
      - base=main
      - label=ready-to-merge
    actions:
      merge:
        method: merge
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: